---
machines:
  sp_web:
    hostname: "sp_web"
    ipv4: "192.168.65.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/spark-2.5/"
      owner: www-data
      group: www-data
    port_map:
    - host: 4430
      guest: 443

  sp_db:
    hostname: "sp_db"
    ipv4: "192.168.65.20"
    playbook: "provisioning/ansible/db_server.yml"
